name: Deploy to EC2
on: [push]

env:
  DOCKER_INSTANCE: 'ec2-user@51.20.3.229'
  PROJECT_DIR: '/home/ec2-user/Minimal-Flask-App'
  DOCKER_IMAGE: 'flask-app'
  DOCKER_TAG: 'latest'  # Folosește un tag static

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare EC2 environment
        run: |
          ssh -o StrictHostKeyChecking=no $DOCKER_INSTANCE "
            mkdir -p $PROJECT_DIR
            [ ! -d '$PROJECT_DIR/.git' ] && git clone https://github.com/botaioana/Minimal-Flask-App.git $PROJECT_DIR || true
          "

      - name: Sync code to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git/' --delete ./ $DOCKER_INSTANCE:$PROJECT_DIR/

      - name: Build and deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no $DOCKER_INSTANCE "
            cd $PROJECT_DIR
            
            # Cleanup previous containers
            docker ps -aq --filter name=$DOCKER_IMAGE | xargs -r docker stop | xargs -r docker rm
            
            # Build with cache
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
            
            # Run new container
            docker run -d \
              --name $DOCKER_IMAGE \
              -p 5000:5000 \
              -e FLASK_ENV=production \
              $DOCKER_IMAGE:$DOCKER_TAG
          "
