name: Deploy to EC2 (Self-Hosted Runner + Amazon Linux 2023)
on: [push]

env:
  APP_INSTANCE: 'ec2-user@13.60.95.182'  # Instanța țintă unde rulează aplicația
  PROJECT_DIR: '/home/ec2-user/Minimal-Flask-App'
  DOCKER_IMAGE: 'flask-app'
  DOCKER_TAG: 'latest'

jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Rulează pe instanța ta EC2 (13.51.205.0)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key for target instance
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Cheia pentru instanța țintă (13.60.95.182)

      - name: Setup EC2 environment (on target instance)
        run: |
          ssh -o StrictHostKeyChecking=no $APP_INSTANCE "
            # Install required packages
            sudo dnf update -y
            sudo dnf install -y docker git
            
            # Start Docker
            sudo systemctl enable docker
            sudo systemctl start docker
            
            # Add ec2-user to docker group
            sudo usermod -aG docker ec2-user
            
            # Prepare project directory
            mkdir -p $PROJECT_DIR
            [ ! -d '$PROJECT_DIR/.git' ] && git clone https://github.com/botaioana/Minimal-Flask-App.git $PROJECT_DIR || true
          "

      - name: Sync code to target instance
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git/' \
            --exclude='.github/' \
            --delete ./ $APP_INSTANCE:$PROJECT_DIR/

      - name: Deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no $APP_INSTANCE "
            cd $PROJECT_DIR
            
            # Force rebuild to avoid cache issues
            docker build --no-cache -t $DOCKER_IMAGE:$DOCKER_TAG .
            
            # Stop and remove old containers
            docker ps -aq --filter name=$DOCKER_IMAGE | xargs -r docker stop | xargs -r docker rm || true
            
            # Run with production settings
            docker run -d \
              --name $DOCKER_IMAGE \
              -p 80:5000 \
              -e FLASK_ENV=production \
              --restart unless-stopped \
              $DOCKER_IMAGE:$DOCKER_TAG
          "
